### PR TITLE
Major clean up and switch to MonoGame

### PR DESCRIPTION
**Pull request by ZackCDLVI**
XNA 4 = MonoGame.

### CODE REVIEW

**Comment by francot514** [comment]
Not necessary to move to monogame, is a tool based application, not a game

**Comment by ZackCDLVI** [comment]
SimsLib uses XNA.

**Comment by francot514** [comment]
Ok, wait but the idea is not to use it, i think the simslib xna for simnhood need to be stripped out, i will only handle bitmaps and not xna textures like for sprite objects..

**Comment by ZackCDLVI** [comment]
But you had Microsoft's XNA libaries in the your repo for SimsLib at the time that I cloned it. Go figure. XD

**Comment by francot514** [comment]
Yes that solved, no problem new simslib for SimNhood do not use xna libraries

**Pull request closed without merging**
